DROP TABLE IF EXISTS `stat_log`;

CREATE TABLE IF NOT EXISTS `stat_log` ( 
 `id` bigint unsigned NOT NULL auto_increment,
 `id_session` varchar(32),
 `id_user` integer unsigned,
 `ip` integer unsigned,
 `proxy` integer unsigned,
 `ref_domain` varchar(50),
 `ref_page` varchar(255),
 `ref_pagequery` varchar(255),
 `ref_catalog` integer unsigned,
 `ref_search_sys` integer unsigned,
 `ref_search_query` varchar(255),
 `ref_mail_sys` integer unsigned,
 `ref_rating` integer unsigned,
 `agent` varchar(255),
 `browser` integer unsigned,
 `os` integer unsigned,
 `acceptlang` varchar(100),
 `date` integer unsigned,
 `time` integer unsigned,
 `domain` varchar(50),
 `request_uri` varchar(255),
 `page` varchar(50),
 `titlepage` varchar(255),
 `language` char(3),
 `page_rateload` double(10,2) unsigned,
 `existspage` enum('1','') default '1',
 `city` integer unsigned,
 `country` integer unsigned,
 PRIMARY KEY  (`id`),
 KEY `id_session` (`id_session`),
 KEY `id_user` (`id_user`),
 KEY `ip` (`ip`),
 KEY `ref_domain` (`ref_domain`),
 KEY `ref_page` (`ref_page`),
 KEY `ref_search_sys` (`ref_search_sys`),
 KEY `ref_search_query` (`ref_search_query`),
 KEY `date` (`date`),
 KEY `time` (`time`),
 KEY `request_uri` (`request_uri`),
 KEY `page` (`page`),
 KEY `titlepage` (`titlepage`)
) ENGINE=innoDB DEFAULT CHARSET=utf8;

