tinyMCE.addI18n('en.images_dlg', {
    title: 'Subir e insertar imagen',
    normal_upload: 'Carga normal',
    multi_upload: 'Multiupload',
    select_file: 'Seleccione fila',
    files_uploaded: 'Archivos subidos',
    upload: 'Subir',
    select_few_files: 'Seleccione algunos archivos',
    browse: 'Navegar&#133;',
    cancel_all_uploads: 'Cancelar todos los archivos subidos',
    loading_content: 'SWFUpload se está cargando. Por favor, espere un momento...',
    long_loading: 'SWFUpload está tardando mucho en cargarse o la carga ha fallado. Por favor, asegúrese de que el lector Flash no está habilitado y que una versión de trabajo del reproductor de Flash instalado.',
    alternate_content: 'We \ 're siento. SWFUpload no se pudo cargar. Es posible que necesite instalar o actualizar Flash Player. Visita el <a href="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash">Adobe sitio web</a> para obtener el Flash Player.',
    insert_image: 'Insertar imagen',
    create_dir: 'Crear dir',
    remove_dir: 'Retire dir',
    cancel_creating: 'Cancelar la creación de',
    cancel_dir_creating: 'Cancelar dir creación',
    create: 'Crear',
    confirm_dir_creating: 'Confirme de dir creación',
    upload_files: 'Subir archivos',
    delete_files: 'Elimine los archivos',
    loading: 'Carga',
    save: 'Salvar',
    edit: 'Editar',
    upload_date: 'Fecha de envío',
    image_size: 'Tamaño de imagen',
    files: 'Files',
    link_to_file: 'Vincular a archivo',
    link_: 'Enlace',
    size: 'Tamaño',
    images: 'Imágenes',
    files: 'Files',
    enter_a_name_for_new_folder: 'Escriba un nombre para la nueva carpeta',
    delete_folder: 'Eliminar carpeta',
    select_files_to_delete: 'Seleccione los archivos que desea eliminar.\n\nNo puede seleccionar varios archivos a la vez, así que mantén pulsado Ctrl mientras los selecciona.',
    delete_file: 'Eliminar archivo',
    files_to_delete: 'Archivos para eliminar',
    continue_: 'Continuar',
    files_selected: 'Los archivos seleccionados',
    files_total: 'Files',
    bytes: 'b',
    kbytes: 'kb',
    mbytes: 'Mb',
    remove: 'Quitar',
    you_can_not_upload: 'No se pueden cargar archivos con la extensión $ext!',
    file_already_added: 'Archivo $file ya se ha agregado',
    all_files: 'Todos los archivos'
});
